-- DBUPDATE-031-0.SQL

-- Insert a new setting for OCR recognition
insert into T_CONFIG (CFG_ID_C, CFG_VALUE_C) values ('OCR_ENABLED', 'true');

-- Create the T_CHAT_MESSAGE table
CREATE TABLE T_CHAT_MESSAGE (
    MSG_ID_C VARCHAR(36) NOT NULL,
    SENDER_ID_C VARCHAR(36) NOT NULL,
    RECEIVER_ID_C VARCHAR(36) NOT NULL,
    CONTENT_C TEXT NOT NULL,
    CREATE_DATE_D TIMESTAMP NOT NULL,
    READ_B BOOLEAN NOT NULL,
    PRIMARY KEY (MSG_ID_C)
);

-- Create indexes for the T_CHAT_MESSAGE table
CREATE INDEX IDX_CHAT_SENDER ON T_CHAT_MESSAGE(SENDER_ID_C);
CREATE INDEX IDX_CHAT_RECEIVER ON T_CHAT_MESSAGE(RECEIVER_ID_C);
CREATE INDEX IDX_CHAT_CREATE_DATE ON T_CHAT_MESSAGE(CREATE_DATE_D);

-- Update the database version
update T_CONFIG set CFG_VALUE_C = '31' where CFG_ID_C = 'DB_VERSION';
